apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking
        image: otniel217/booking-service:1.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: booking-config
        - secretRef:
            name: booking-secret
