apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      containers:
      - name: movies-service
        image: otniel217/movies-service:1.0
        workingDir: /home/nupp/app
        ports:
        - containerPort: 3000
        command: ["dumb-init", "npm", "start"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
