apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: <ton-registry>/payment-service:latest
        workingDir: /home/nupp/app
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: payment-service-config
        command: ["dumb-init", "npm", "start"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
